# Generated by Django 4.2 on 2025-12-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(help_text='ID único del municipio', primary_key=True, serialize=False)),
                ('municipio', models.CharField(help_text='Nombre del municipio', max_length=255)),
                ('estado', models.BooleanField(default=True, help_text='Estado del municipio (activo/inactivo)')),
                ('departamento', models.ForeignKey(db_column='departamento_id', help_text='Departamento al que pertenece', on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['departamento__departamento', 'municipio'],
            },
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['departamento', 'municipio'], name='idx_mun_dept_nombre'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['estado'], name='idx_mun_estado'),
        ),
    ]
