# Generated by Django 4.2 on 2026-01-11 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTramite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre del trámite', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del trámite', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del trámite en pesos colombianos', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el trámite está activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Trámite',
                'verbose_name_plural': 'historical Trámites',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del trámite', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del trámite', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del trámite en pesos colombianos', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el trámite está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'db_table': 'tramites',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['nombre'], name='tramites_nombre_01c1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tramite',
            index=models.Index(fields=['is_active'], name='tramites_is_acti_b8ff57_idx'),
        ),
        migrations.AddField(
            model_name='historicaltramite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
