# Generated by Django 4.2 on 2026-01-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltramite',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='precio',
        ),
    ]
