# Generated by Django 4.2 on 2026-01-18 14:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preparacion', '0009_historicalpreparacion_tramite_preparacion_tramite'),
        ('tramites', '0002_remove_historicaltramite_precio_and_more'),
        ('municipios', '0001_initial'),
        ('proveedores', '0005_alter_municipio_unique_together_and_more'),
        ('departamentos', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derechos_tramite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derechos/precio del trámite', max_digits=12)),
                ('servicio_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio que cobra la empresa al cliente', max_digits=12)),
                ('servicio_gestor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio que se paga al gestor', max_digits=12)),
                ('transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gastos de transporte/envíos', max_digits=12)),
                ('bonificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonificación al gestor', max_digits=12)),
                ('anticipos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Anticipos entregados al gestor', max_digits=12)),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, help_text='Tipo de vehículo', max_length=50)),
                ('fecha_finalizado', models.DateTimeField(auto_now_add=True, help_text='Fecha de finalización del trámite')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='pendiente', help_text='Estado de la liquidación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente del trámite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='clientes.cliente')),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento del trámite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='departamentos.departamento')),
                ('municipio', models.ForeignKey(blank=True, help_text='Municipio del trámite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='municipios.municipio')),
                ('preparacion', models.OneToOneField(help_text='Trámite de preparación asociado', on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='preparacion.preparacion')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Gestor que realizó el trámite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='proveedores.proveedor')),
                ('tramite', models.ForeignKey(blank=True, help_text='Tipo de trámite realizado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'db_table': 'liquidaciones',
                'ordering': ['-fecha_finalizado'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLiquidacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('derechos_tramite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derechos/precio del trámite', max_digits=12)),
                ('servicio_empresa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio que cobra la empresa al cliente', max_digits=12)),
                ('servicio_gestor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio que se paga al gestor', max_digits=12)),
                ('transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gastos de transporte/envíos', max_digits=12)),
                ('bonificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonificación al gestor', max_digits=12)),
                ('anticipos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Anticipos entregados al gestor', max_digits=12)),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, help_text='Tipo de vehículo', max_length=50)),
                ('fecha_finalizado', models.DateTimeField(blank=True, editable=False, help_text='Fecha de finalización del trámite')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='pendiente', help_text='Estado de la liquidación', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, help_text='Departamento del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, db_constraint=False, help_text='Municipio del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='municipios.municipio')),
                ('preparacion', models.ForeignKey(blank=True, db_constraint=False, help_text='Trámite de preparación asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='preparacion.preparacion')),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, help_text='Gestor que realizó el trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor')),
                ('tramite', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de trámite realizado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'historical Liquidación',
                'verbose_name_plural': 'historical Liquidaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['placa'], name='liquidacion_placa_f63c46_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['estado'], name='liquidacion_estado_397bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['fecha_finalizado'], name='liquidacion_fecha_f_6702ee_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['proveedor'], name='liquidacion_proveed_6e1e39_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['tramite'], name='liquidacion_tramite_dd9caa_idx'),
        ),
    ]
