# Generated by Django 4.2 on 2026-01-12 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0005_alter_municipio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_proveedor', models.DecimalField(decimal_places=2, help_text='Precio del servicio que cobra el proveedor', max_digits=10)),
                ('servicio_empresa', models.DecimalField(decimal_places=2, help_text='Precio del servicio que cobra la empresa', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tarifa está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que gestiona este tránsito', on_delete=django.db.models.deletion.PROTECT, related_name='transito_tarifas', to='proveedores.proveedor')),
                ('tramite', models.ForeignKey(help_text='Trámite asociado a esta tarifa', on_delete=django.db.models.deletion.PROTECT, related_name='transito_tarifas', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'Tránsito Tarifa',
                'verbose_name_plural': 'Tránsitos Tarifas',
                'db_table': 'transito_tarifas',
                'ordering': ['tramite__nombre', 'proveedor__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransitoTarifa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('servicio_proveedor', models.DecimalField(decimal_places=2, help_text='Precio del servicio que cobra el proveedor', max_digits=10)),
                ('servicio_empresa', models.DecimalField(decimal_places=2, help_text='Precio del servicio que cobra la empresa', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la tarifa está activa')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, db_constraint=False, help_text='Proveedor que gestiona este tránsito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor')),
                ('tramite', models.ForeignKey(blank=True, db_constraint=False, help_text='Trámite asociado a esta tarifa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tramites.tramite')),
            ],
            options={
                'verbose_name': 'historical Tránsito Tarifa',
                'verbose_name_plural': 'historical Tránsitos Tarifas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='transitotarifa',
            index=models.Index(fields=['tramite', 'proveedor'], name='transito_ta_tramite_d44760_idx'),
        ),
        migrations.AddIndex(
            model_name='transitotarifa',
            index=models.Index(fields=['is_active'], name='transito_ta_is_acti_cea398_idx'),
        ),
        migrations.AddIndex(
            model_name='transitotarifa',
            index=models.Index(fields=['created_at'], name='transito_ta_created_36f71e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transitotarifa',
            unique_together={('tramite', 'proveedor')},
        ),
    ]
