# Generated by Django 4.2 on 2026-02-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transitotarifas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transitotarifa',
            new_name='transito_ta_departa_2e2423_idx',
            old_name='transito_ta_departa_0e7c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifa',
            new_name='transito_ta_is_acti_cea398_idx',
            old_name='transito_ta_is_acti_c5f8e9_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifa',
            new_name='transito_ta_created_36f71e_idx',
            old_name='transito_ta_created_d6e7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifagestor',
            new_name='transito_ta_tramite_7a4229_idx',
            old_name='transito_ta_tramite_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifagestor',
            new_name='transito_ta_created_30b45c_idx',
            old_name='transito_ta_created_0j1k2l_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifatramite',
            new_name='transito_ta_transit_44a048_idx',
            old_name='transito_ta_transit_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='transitotarifatramite',
            new_name='transito_ta_created_2c2cef_idx',
            old_name='transito_ta_created_4d5e6f_idx',
        ),
    ]
