# Generated by Django 4.2 on 2025-12-19 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('municipios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Motocicleta', 'Motocicleta'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Otro', 'Otro')], help_text='Tipo de vehículo', max_length=20)),
                ('estado', models.CharField(choices=[('en_verificacion', 'En Verificación'), ('para_radicacion', 'Para Radicación'), ('en_novedad', 'En Novedad'), ('enviado_tracker', 'Enviado a Tracker')], default='en_verificacion', help_text='Estado actual del trámite', max_length=20)),
                ('paquete', models.CharField(blank=True, help_text='Ruta o nombre de la carpeta de archivos', max_length=255, null=True)),
                ('lista_documentos', models.JSONField(blank=True, default=list, help_text='Lista de documentos requeridos con su estado de completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('departamento', models.ForeignKey(db_column='departamento_id', help_text='Departamento del trámite', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to='departamentos.departamento')),
                ('municipio', models.ForeignKey(db_column='municipio_id', help_text='Municipio del trámite', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to='municipios.municipio')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trámite en Preparación',
                'verbose_name_plural': 'Trámites en Preparación',
                'db_table': 'preparacion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['placa'], name='idx_prep_placa'),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['estado'], name='idx_prep_estado'),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['departamento', 'municipio'], name='idx_prep_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['created_at'], name='idx_prep_fecha'),
        ),
    ]
