# Generated by Django 4.2 on 2025-12-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo PDF o imagen (PNG, JPG)', upload_to='preparacion/%Y/%m/%d/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('tipo_archivo', models.CharField(help_text='Tipo MIME del archivo (application/pdf, image/png, etc.)', max_length=50)),
                ('tamaño', models.IntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de carga')),
                ('tramite', models.ForeignKey(help_text='Trámite al que pertenece este archivo', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='preparacion.preparacion')),
            ],
            options={
                'verbose_name': 'Archivo de Trámite',
                'verbose_name_plural': 'Archivos de Trámites',
                'db_table': 'preparacion_archivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='preparacionarchivo',
            index=models.Index(fields=['tramite'], name='idx_prep_arch_tramite'),
        ),
    ]
