# Generated by Django 4.2 on 2025-12-19 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preparacion', '0002_preparacionarchivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPreparacionArchivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('archivo', models.TextField(help_text='Archivo PDF o imagen (PNG, JPG)', max_length=100)),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('tipo_archivo', models.CharField(help_text='Tipo MIME del archivo (application/pdf, image/png, etc.)', max_length=50)),
                ('tamaño', models.IntegerField(help_text='Tamaño del archivo en bytes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de carga')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico', to='preparacion.preparacionarchivo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, db_constraint=False, help_text='Trámite al que pertenece este archivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='preparacion.preparacion')),
            ],
            options={
                'verbose_name': 'Historial de Archivo',
                'verbose_name_plural': 'historical Archivos de Trámites',
                'db_table': 'history_preparacion_archivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPreparacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Motocicleta', 'Motocicleta'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Otro', 'Otro')], help_text='Tipo de vehículo', max_length=20)),
                ('estado', models.CharField(choices=[('en_verificacion', 'En Verificación'), ('para_radicacion', 'Para Radicación'), ('en_novedad', 'En Novedad'), ('enviado_tracker', 'Enviado a Tracker')], default='en_verificacion', help_text='Estado actual del trámite', max_length=20)),
                ('paquete', models.CharField(blank=True, help_text='Ruta o nombre de la carpeta de archivos', max_length=255, null=True)),
                ('lista_documentos', models.JSONField(blank=True, default=list, help_text='Lista de documentos requeridos con su estado de completado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', db_constraint=False, help_text='Departamento del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico', to='preparacion.preparacion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, db_column='municipio_id', db_constraint=False, help_text='Municipio del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='municipios.municipio')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Preparación',
                'verbose_name_plural': 'historical Trámites en Preparación',
                'db_table': 'history_preparacion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
