# Generated by Django 4.2 on 2025-12-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0003_historicalpreparacionarchivo_historicalpreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='estado_modulo',
            field=models.IntegerField(default=1, help_text='Estado del módulo: 1-En preparación, 2-En Tracker, 3-En Finalizados, 0-Archivados'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='estado_modulo',
            field=models.IntegerField(default=1, help_text='Estado del módulo: 1-En preparación, 2-En Tracker, 3-En Finalizados, 0-Archivados'),
        ),
    ]
