# Generated by Django 4.2 on 2025-12-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_alter_municipio_unique_together_and_more'),
        ('preparacion', '0004_historicalpreparacion_estado_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='estado_detalle',
            field=models.TextField(blank=True, help_text='Descripción detallada del estado (alimentado por Proveedores en Tracker)', null=True),
        ),
        migrations.AddField(
            model_name='historicalpreparacion',
            name='fecha_recepcion_municipio',
            field=models.DateField(blank=True, help_text='Fecha de recepción en municipio (usado en módulo Tracker)', null=True),
        ),
        migrations.AddField(
            model_name='historicalpreparacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', db_constraint=False, help_text='Proveedor encargado del trámite (usado en módulo Tracker)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='estado_detalle',
            field=models.TextField(blank=True, help_text='Descripción detallada del estado (alimentado por Proveedores en Tracker)', null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='fecha_recepcion_municipio',
            field=models.DateField(blank=True, help_text='Fecha de recepción en municipio (usado en módulo Tracker)', null=True),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', help_text='Proveedor encargado del trámite (usado en módulo Tracker)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='historicalpreparacion',
            name='estado',
            field=models.CharField(choices=[('en_verificacion', 'En Verificación'), ('para_radicacion', 'Para Radicación'), ('en_novedad', 'En Novedad'), ('enviado_tracker', 'Enviado a Tracker'), ('en_radicacion', 'En Radicación'), ('con_novedad', 'Con Novedad'), ('finalizado', 'Finalizado')], default='en_verificacion', help_text='Estado actual del trámite', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='estado',
            field=models.CharField(choices=[('en_verificacion', 'En Verificación'), ('para_radicacion', 'Para Radicación'), ('en_novedad', 'En Novedad'), ('enviado_tracker', 'Enviado a Tracker'), ('en_radicacion', 'En Radicación'), ('con_novedad', 'Con Novedad'), ('finalizado', 'Finalizado')], default='en_verificacion', help_text='Estado actual del trámite', max_length=20),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['estado_modulo'], name='idx_prep_estado_modulo'),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['proveedor'], name='idx_prep_proveedor'),
        ),
        migrations.AddIndex(
            model_name='preparacion',
            index=models.Index(fields=['fecha_recepcion_municipio'], name='idx_prep_fecha_recep'),
        ),
    ]
