# Generated by Django 4.2 on 2025-12-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0005_historicalpreparacion_estado_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='estado_tracker',
            field=models.IntegerField(default=0, help_text='Estado en Tracker: 0-No tiene tracker, 1-En radicación, 2-Con Novedad, 3-Finalizado'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='estado_tracker',
            field=models.IntegerField(default=0, help_text='Estado en Tracker: 0-No tiene tracker, 1-En radicación, 2-Con Novedad, 3-Finalizado'),
        ),
    ]
