# Generated by Django 4.2 on 2025-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0006_historicalpreparacion_estado_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreparacion',
            name='estado_tracker',
            field=models.CharField(choices=[('sin_tracker', 'Sin Tracker'), ('en_radicacion', 'En Radicación'), ('con_novedad', 'Con Novedad'), ('finalizado', 'Finalizado')], default='sin_tracker', help_text='Estado actual del trámite en módulo Tracker', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='estado_tracker',
            field=models.CharField(choices=[('sin_tracker', 'Sin Tracker'), ('en_radicacion', 'En Radicación'), ('con_novedad', 'Con Novedad'), ('finalizado', 'Finalizado')], default='sin_tracker', help_text='Estado actual del trámite en módulo Tracker', max_length=20),
        ),
    ]
