# Generated by Django 4.2 on 2026-01-15 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('preparacion', '0007_alter_historicalpreparacion_estado_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_id', db_constraint=False, help_text='Cliente asociado al trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cliente_id', help_text='Cliente asociado al trámite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to='clientes.cliente'),
        ),
    ]
