# Generated by Django 4.2 on 2026-01-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_remove_historicaltramite_precio_and_more'),
        ('preparacion', '0008_historicalpreparacion_cliente_preparacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='tramite',
            field=models.ForeignKey(blank=True, db_column='tramite_id', db_constraint=False, help_text='Trámite asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tramites.tramite'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='tramite',
            field=models.ForeignKey(blank=True, db_column='tramite_id', help_text='Trámite asociado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_preparacion', to='tramites.tramite'),
        ),
    ]
