# Generated by Django 4.2 on 2026-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0009_historicalpreparacion_tramite_preparacion_tramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreparacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del trámite'),
        ),
        migrations.AddField(
            model_name='preparacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del trámite'),
        ),
    ]
