# Generated by Django 4.2 on 2026-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0010_historicalpreparacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreparacion',
            name='estado_tracker',
            field=models.CharField(choices=[('sin_tracker', 'Sin tracker'), ('en_radicacion', 'En radicación'), ('pte_agenda', 'Pendiente de agenda'), ('con_novedad', 'Con novedad'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='sin_tracker', help_text='Estado actual del trámite en módulo Tracker', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparacion',
            name='estado_tracker',
            field=models.CharField(choices=[('sin_tracker', 'Sin tracker'), ('en_radicacion', 'En radicación'), ('pte_agenda', 'Pendiente de agenda'), ('con_novedad', 'Con novedad'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='sin_tracker', help_text='Estado actual del trámite en módulo Tracker', max_length=20),
        ),
    ]
