# Generated by Django 4.2 on 2026-01-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('razon_social', models.CharField(help_text='Razón social del cliente', max_length=255)),
                ('nit', models.CharField(db_index=True, help_text='NIT del cliente', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad_id', db_constraint=False, help_text='Ciudad/Municipio del cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='municipios.municipio')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', db_constraint=False, help_text='Departamento del cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('razon_social', models.CharField(help_text='Razón social del cliente', max_length=255)),
                ('nit', models.CharField(help_text='NIT del cliente', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad_id', help_text='Ciudad/Municipio del cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='municipios.municipio')),
                ('departamento', models.ForeignKey(db_column='departamento_id', help_text='Departamento del cliente', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nit'], name='idx_cliente_nit'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['departamento', 'ciudad'], name='idx_cliente_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['is_active'], name='idx_cliente_activo'),
        ),
    ]
