# Generated by Django 4.2 on 2025-12-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='municipio',
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['departamento', 'nombre'],
                'unique_together': {('nombre', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipios',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='proveedores.municipio'),
        ),
    ]
