# Generated by Django 4.2 on 2025-12-19 00:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0003_remove_proveedor_municipio_municipio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-created_at', 'nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.CharField(db_index=True, help_text='Departamento al que pertenece', max_length=100),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_encargado',
            field=models.CharField(db_index=True, help_text='Código único identificador del encargado', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(db_index=True, help_text='Departamento principal de operación', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el proveedor está activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='municipios',
            field=models.ManyToManyField(blank=True, help_text='Municipios donde el proveedor tiene cobertura', related_name='proveedores', to='proveedores.municipio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(help_text='Nombre o razón social del proveedor', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='transitos_habilitados',
            field=models.JSONField(blank=True, default=list, help_text="Lista de códigos de tránsitos habilitados (ej: ['001', '002'])"),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', help_text='Usuario asociado al proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(help_text='Número de WhatsApp (10 dígitos)', max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número válido de WhatsApp colombiano (ej: 3001234567 o +573001234567)', regex='^\\+?57?3\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['departamento', 'nombre'], name='idx_mun_dept_nombre'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['codigo_encargado'], name='idx_prov_codigo'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['is_active', 'departamento'], name='idx_prov_active_dept'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['-created_at'], name='idx_prov_created'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['whatsapp'], name='idx_prov_whatsapp'),
        ),
    ]
