# Generated by Django 4.2 on 2025-12-19 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0004_alter_proveedor_options_alter_municipio_departamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='idx_prov_codigo',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='idx_prov_active_dept',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='idx_prov_created',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='idx_prov_whatsapp',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='municipios',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_encargado',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='transitos_habilitados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
