# Generated by Django 4.2 on 2025-12-23 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0005_alter_municipio_unique_together_and_more'),
        ('municipios', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('preparacion', '0003_historicalpreparacionarchivo_historicalpreparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion_municipio', models.DateField(blank=True, help_text='Fecha en que el trámite fue recibido en el municipio (editable manualmente)', null=True)),
                ('estado', models.CharField(choices=[('EN_RADICACION', 'En Radicación'), ('CON_NOVEDAD', 'Con Novedad'), ('FINALIZADO', 'Finalizado')], default='EN_RADICACION', help_text='Estado actual del trámite', max_length=20)),
                ('estado_detalle', models.TextField(blank=True, help_text='Descripción explícita del estado actual (opcional, alimentado por Proveedores)', null=True)),
                ('placa', models.CharField(db_index=True, help_text='Placa del vehículo', max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('MOTOCICLETA', 'Motocicleta'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('OTRO', 'Otro')], help_text='Tipo de vehículo del trámite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('departamento', models.ForeignKey(db_column='departamento_id', help_text='Departamento del trámite', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_tracker', to='departamentos.departamento')),
                ('municipio', models.ForeignKey(db_column='municipio_id', help_text='Municipio del trámite', on_delete=django.db.models.deletion.PROTECT, related_name='tramites_tracker', to='municipios.municipio')),
                ('preparacion', models.ForeignKey(blank=True, db_column='preparacion_id', help_text='Trámite de preparación asociado (paquete PDF)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radicaciones', to='preparacion.preparacion')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', help_text='Proveedor encargado del trámite (identificado por codigo_encargado)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_tracker', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario que creó el registro en el sistema', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radicaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trámite en Tracker',
                'verbose_name_plural': 'Trámites en Tracker',
                'db_table': 'tracker',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTracker',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_recepcion_municipio', models.DateField(blank=True, help_text='Fecha en que el trámite fue recibido en el municipio (editable manualmente)', null=True)),
                ('estado', models.CharField(choices=[('EN_RADICACION', 'En Radicación'), ('CON_NOVEDAD', 'Con Novedad'), ('FINALIZADO', 'Finalizado')], default='EN_RADICACION', help_text='Estado actual del trámite', max_length=20)),
                ('estado_detalle', models.TextField(blank=True, help_text='Descripción explícita del estado actual (opcional, alimentado por Proveedores)', null=True)),
                ('placa', models.CharField(db_index=True, help_text='Placa del vehículo', max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('MOTOCICLETA', 'Motocicleta'), ('CAMIONETA', 'Camioneta'), ('CAMION', 'Camión'), ('BUS', 'Bus'), ('TAXI', 'Taxi'), ('OTRO', 'Otro')], help_text='Tipo de vehículo del trámite', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', db_constraint=False, help_text='Departamento del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departamentos.departamento')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico', to='tracker.tracker')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, db_column='municipio_id', db_constraint=False, help_text='Municipio del trámite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='municipios.municipio')),
                ('preparacion', models.ForeignKey(blank=True, db_column='preparacion_id', db_constraint=False, help_text='Trámite de preparación asociado (paquete PDF)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='preparacion.preparacion')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', db_constraint=False, help_text='Proveedor encargado del trámite (identificado por codigo_encargado)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', db_constraint=False, help_text='Usuario que creó el registro en el sistema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Tracker',
                'verbose_name_plural': 'historical Trámites en Tracker',
                'db_table': 'history_tracker',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['placa'], name='idx_tracker_placa'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['estado'], name='idx_tracker_estado'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['proveedor'], name='idx_tracker_proveedor'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['fecha_recepcion_municipio'], name='idx_tracker_fecha_recep'),
        ),
        migrations.AddIndex(
            model_name='tracker',
            index=models.Index(fields=['created_at'], name='idx_tracker_created'),
        ),
    ]
