# Generated by Django 4.2 on 2025-12-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='preparacion',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='HistoricalTracker',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
