# Generated by Django 4.2 on 2025-12-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(help_text='Código DANE del departamento', primary_key=True, serialize=False)),
                ('departamento', models.CharField(help_text='Nombre del departamento', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['departamento'],
            },
        ),
    ]
